language: elixir
elixir:
  - 1.6.0
otp_release:
  - 20.3
services:
  - postgres
script:
  - mix deps.get
  - MIX_ENV=test mix do compile --warnings-as-errors
  - mix credo --strict
  - mix dialyzer
  - MIX_ENV=test mix ecto.create --repo Catalog.Repo
  - MIX_ENV=test mix load_usda_catalog
  - MIX_ENV=test mix coveralls.travis --umbrella

